version: '3.3'

services:
  dagster-dagit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  dagster-daemon:
    build:
      context: .
      dockerfile: Dockerfile
    command: "dagster-daemon run"

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    env_file: .env
    ports:
      - "$VECTOR_STORE_PORT:$VECTOR_STORE_PORT"
    volumes:
      - "index_data:/chroma/.chroma/index"

volumes:
  index_data:
    driver: local
