import os

SAMPLING_AMOUNT = int(os.getenv("SAMPLING_AMOUNT", "1"))
SAMPLING_RATE = float(os.getenv("SAMPLING_RATE", "0.5"))
SAMPLING_MIN_ITEM_SET_NODES = int(os.getenv("SAMPLING_MIN_ITEM_SET_NODES", "100"))
SAMPLING_MAX_ITEM_SET_NODES = int(os.getenv("SAMPLING_MAX_ITEM_SET_NODES", "1000"))
SAMPLING_ATTEMPTS = int(os.getenv("SAMPLING_ATTEMPTS", "100"))
